# Generated by Django 3.1.4 on 2020-12-11 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_simulate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulate',
            name='content',
        ),
    ]
