# Generated by Django 3.1.4 on 2020-12-11 15:29

from django.db import migrations, models
from rest_framework import serializers

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='sports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                
            ],
        ),
    ]
