# Generated by Django 3.1.4 on 2020-12-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_sports'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data',
        ),
        migrations.DeleteModel(
            name='simulate',
        ),
        migrations.DeleteModel(
            name='sports',
        ),
    ]
