# Generated by Django 3.1.4 on 2020-12-19 18:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='value',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=None),
        ),
    ]
