# Generated by Django 3.1.4 on 2020-12-20 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201219_2338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='output',
        ),
    ]
